FROM node:20-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY apps/web/package.json ./apps/web/
COPY libs ./libs
COPY packages ./packages

RUN npm install -g pnpm && pnpm install --frozen-lockfile

EXPOSE 5173

CMD ["pnpm", "nx", "run", "web:serve"]
