"""add user_id to places

Revision ID: 0253cd95755d
Revises: 09e1a27a2780
Create Date: 2026-07-17 02:27:43.277286

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0253cd95755d"
down_revision: Union[str, Sequence[str], None] = "09e1a27a2780"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("places", sa.Column("user_id", sa.String(), nullable=False))
    op.create_foreign_key(None, "places", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "places", type_="foreignkey")
    op.drop_column("places", "user_id")
    # ### end Alembic commands ###
