"""schema update

Revision ID: 6d5fc615fa31
Revises: 6d7cfee35fa0
Create Date: 2026-08-15 22:17:52.492382

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6d5fc615fa31"
down_revision: str | Sequence[str] | None = "6d7cfee35fa0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
